development:
  adapter: sqlite3
  database: db/shopify_app.sqlite3
  pool: 5

test:
  adapter: sqlite3
  database: "db/test.sqlite3"
  pool: 8

production:
  adapter: postgres
  database: nw-fulfillment